[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "KyngNoodle"
name = "Cursed_Scrap"
description = "Only allows cursed scrap to spawn."
websiteUrl = "https://github.com/KyngNoodle/Lethal-Company-Cursed-Scrap-Mod"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icons/icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../CursedScrap/bin/com.github.kyngnoodle.cursed_scrap.dll"
target = "/BepInEx/plugins/com.github.kyngnoodle.cursed_scrap.dll"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "mods", "bepinex", ]
